### ISSUE TITLE
"config.xbx not found"

### ISSUE THREAD

**Issue by Hordini** [MobCat/UIXinator#1]
Using the latest Iconinator build from [releases](https://github.com/MobCat/UIXinator/releases)
Also using the built-in FTP app from StellarOS

```
Iconinator 20240828
Automatically building an icon pack for the games launcher,
based on the content you have installed on your Xbox HDD.

Loading default settings.ini
Connecting to xbox:xbox@192.168.1.237:21

ERROR: Is UIX Lite installed onto C:?
I can't seem to find your config.xbx.
FTP Error: C/UIX Configs/config.xbx: 550 File C/UIX Configs/config.xbx not found
Press Enter to exit.
```
![filezilla_OvX4Ju5XjC](https://github.com/user-attachments/assets/453a43a7-5ece-4ca9-94ea-8a7eeba9c680)

Not sure if I'm doing something wrong, but the directory seems like it should be valid.
Also worth noting, I had an issue generating the `settings.ini` file and had to manually download it from your message on Discord a bit ago. Don't think it's related though.

**Comment by Hordini** [comment]
So I gave it another go using the FTP Server built-in to XBMC4Gamers, and that worked without issue.

Unsure if it's a problem with this project, or StellarOS, but at the very least it's something to keep in mind for others that may run into the same problem. 🤔

Feel free to close if this issue isn't relevant to this project.

**Comment by MobCat** [comment]
Yeah it appears to be something funky on StellarOS and how it has ftp implemented. (probs same  sorta issues old avalaunch ftp server)
But we are also battling the default ftp library in python as well.
So we could "fix" it, like how we have a fix for xemu, but as I do not have this modchip, and afaik no real way to run StellarOS outside of that modchip. I am unable to diagnose this to fix it.
So gonna have to mark this as "out of scope" for now. (if anyone else wants to have a look, be my guest / make a pull request)
I'm happy to fix things when I can, but I'm also really bad at this, so I can only do what I can.
